---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/activities":
    get:
      summary: Lists all activities
      tags:
      - " Activities"
      responses:
        '200':
          description: lists activities
          content:
            application/json:
              schema:
                type: object
                properties:
                  activities:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        content:
                          type: string
                        image:
                          type: string
                      required:
                      - id
                      - name
                      - content
    post:
      summary: Creates an activity
      tags:
      - " Activities"
      security:
      - bearer_auth: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: Activity created
          content:
            application/json:
              schema:
                type: object
                properties:
                  activity:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      content:
                        type: string
                      image:
                        type: string
        '401':
          description: unauthorized
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                activity:
                  type: object
                  properties:
                    name:
                      type: string
                    content:
                      type: string
                    image:
                      type: string
                  required:
                  - name
                  - content
  "/api/activities/{id}":
    put:
      summary: Updates an activity
      tags:
      - " Activities"
      security:
      - bearer_auth: {}
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: updated succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  activity:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      content:
                        type: string
                      image:
                        type: string
        '401':
          description: unauthorized
        '422':
          description: invalid request
        '404':
          description: not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                content:
                  type: string
                image:
                  type: string
    delete:
      summary: Deletes an activity
      tags:
      - " Activities"
      security:
      - bearer_auth: {}
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: deleted succesfully
        '401':
          description: unauthorized
        '404':
          description: not found
  "/api/auth/register":
    post:
      summary: Registers a new User
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: returns new registered user
          content:
            application/json:
              example:
                user:
                  id: 23
                  first_name: Guido
                  last_name: Medina
                  email: guido@gmail.com
                  role:
                    id: 1
                    name: admin
                    description: 'null'
                  image: www.myimage.com/image.jpg
                  token: jhaskdhJKASDAjakAHSuioS2JS8ns
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      first_name:
                        type: string
                      last_name:
                        type: string
                      email:
                        type: string
                      role:
                        type: object
                        properties:
                          id:
                            type: integer
                          name:
                            type: string
                          description:
                            type: string
                      image:
                        type: string
                      token:
                        type: string
        '400':
          description: no params are sent
        '422':
          description: invalid params are sent
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    first_name:
                      type: string
                    last_name:
                      type: string
                    email:
                      type: string
                    role_id:
                      type: integer
                    image:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                  requires:
                  - first_name
                  - last_name
                  - email
                  - password
                  - password_confirmation
  "/api/auth/login":
    post:
      summary: Logins a user
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: logins a new user
          content:
            application/json:
              example:
                user:
                  id: 23
                  first_name: Guido
                  last_name: Medina
                  email: guido@gmail.com
                  role:
                    id: 1
                    name: admin
                    description: 'null'
                  image: www.myimage.com/image.jpg
                  token: jhaskdhJKASDAjakAHSuioS2JS8ns
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      first_name:
                        type: string
                      last_name:
                        type: string
                      email:
                        type: string
                      role:
                        type: object
                        properties:
                          id:
                            type: integer
                          name:
                            type: string
                          description:
                            type: string
                      image:
                        type: string
                      token:
                        type: string
        '400':
          description: invalid params
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  requires:
                  - email
                  - password
  "/api/auth/me":
    get:
      summary: Returns the current user info
      tags:
      - Authentication
      security:
      - bearer_auth: {}
      responses:
        '200':
          description: returns the current user info
          content:
            application/json:
              example:
                user:
                  id: 23
                  first_name: Guido
                  last_name: Medina
                  email: guido@gmail.com
                  role:
                    id: 1
                    name: admin
                    description: 'null'
                  image: www.myimage.com/image.jpg
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      first_name:
                        type: string
                      last_name:
                        type: string
                      email:
                        type: string
                      role:
                        type: object
                        properties:
                          id:
                            type: integer
                          name:
                            type: string
                          description:
                            type: string
                      image:
                        type: string
        '401':
          description: unauthorized request
  "/api/categories":
    post:
      summary: Post a category
      tags:
      - Categories
      security:
      - Bearer: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: Category created
        '401':
          description: Unauthorized
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
              required:
              - name
    get:
      summary: Get all categories
      tags:
      - Categories
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: List of categories
  "/api/categories/{id}":
    put:
      summary: Updates a category
      tags:
      - Categories
      security:
      - Bearer: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Updated successfully
        '401':
          description: Unauthorized
        '422':
          description: Invalid request
        '404':
          description: Not found
    delete:
      summary: Delete a category
      tags:
      - Categories
      security:
      - Bearer: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Not found
  "/api/chats":
    get:
      summary: Get all chats
      tags:
      - Chats
      security:
      - bearer_auth: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: List of chats
          content:
            application/json:
              schema:
                type: object
                properties:
                  chats:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                        created_at:
                          type: string
                        users:
                          type: array
                          items:
                            properties:
                              id:
                                type: integer
                              first_name:
                                type: string
                              last_name:
                                type: string
                              role:
                                type: object
                                items:
                                  id:
                                    type: integer
                                  name:
                                    type: string
                                  description:
                                    type: string
                              image:
                                type: string
  "/api/comments":
    get:
      summary: Get all comments
      tags:
      - Comments
      security:
      - bearer_auth: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: list all comments
          content:
            application/json:
              schema:
                type: object
                properties:
                  comments:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                        content:
                          type: string
        '401':
          description: unauthorized
    post:
      summary: "/api/comments"
      tags:
      - Comments
      security:
      - bearer_auth: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: comment created
          content:
            application/json:
              schema:
                type: object
                properties:
                  comments:
                    type: object
                    items:
                      properties:
                        id:
                          type: integer
                        content:
                          type: string
        '401':
          description: unauthorized
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                comment:
                  type: object
                  items:
                    properties:
                      id:
                        type: integer
                      content:
                        type: string
                      new_id:
                        type: integer
                required:
                - new_id
  "/api/comments/{id}":
    put:
      summary: Updates a comment
      tags:
      - Comments
      security:
      - bearer_auth: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  comment:
                    type: object
                    items:
                      properties:
                        id:
                          type: integer
                        content:
                          type: string
        '401':
          description: unauthorized
        '422':
          description: invalid request
        '404':
          description: not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
    delete:
      summary: Delete a comment
      tags:
      - Comments
      security:
      - bearer_auth: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: deleted successfully
        '401':
          description: unauthorized
        '404':
          description: not found
  "/api/members":
    post:
      summary: Creates a member
      tags:
      - Members
      security:
      - bearer_auth: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: member created
          content:
            application/json:
              schema:
                type: object
                properties:
                  member:
                    type: object
                    items:
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        facebook_url:
                          type: string
                          nullable: true
                        linkedin_url:
                          type: string
                          nullable: true
                        instagram_url:
                          type: string
                          nullable: true
                        description:
                          type: string
                          nullable: true
        '401':
          description: unauthorized
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                member:
                  type: object
                  items:
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      facebook_url:
                        type: string
                        nullable: true
                      linkedin_url:
                        type: string
                        nullable: true
                      instagram_url:
                        type: string
                        nullable: true
                      description:
                        type: string
                        nullable: true
              required:
              - name
    get:
      summary: Get all members
      tags:
      - Members
      responses:
        '200':
          description: list of members
          content:
            application/json:
              schema:
                type: object
                properties:
                  members:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        facebook_url:
                          type: string
                          nullable: true
                        linkedin_url:
                          type: string
                          nullable: true
                        instagram_url:
                          type: string
                          nullable: true
                        description:
                          type: string
                          nullable: true
  "/api/members/{id}":
    put:
      summary: Updates a member
      tags:
      - Members
      security:
      - bearer_auth: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  member:
                    type: object
                    items:
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        facebook_url:
                          type: string
                          nullable: true
                        linkedin_url:
                          type: string
                          nullable: true
                        instagram_url:
                          type: string
                          nullable: true
                        description:
                          type: string
                          nullable: true
        '401':
          description: unauthorized
        '422':
          description: invalid request
        '404':
          description: not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                facebook_url:
                  type: string
                  nullable: true
                linkedin_url:
                  type: string
                  nullable: true
                instagram_url:
                  type: string
                  nullable: true
                description:
                  type: string
                  nullable: true
    delete:
      summary: Delete a member
      tags:
      - Members
      security:
      - bearer_auth: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: deleted successfully
        '401':
          description: unauthorized
        '404':
          description: not found
  "/api/messages/{id}":
    get:
      summary: Get a message details
      tags:
      - Messages
      security:
      - bearer_auth: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    items:
                      id:
                        type: integer
                      detail:
                        type: string
                      chat:
                        type: object
                        items:
                          id:
                            type: integer
        '404':
          description: message not found
        '401':
          description: unauthorized
  "/api/chats/{id}/messages":
    post:
      summary: Sent a message
      tags:
      - Messages
      security:
      - bearer_auth: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: message created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    items:
                      id:
                        type: integer
                      detail:
                        type: string
        '401':
          description: unauthorized
        '422':
          description: invalid request
        '400':
          description: bad request
        '404':
          description: chat not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: object
                  items:
                    properties:
                      detail:
                        type: string
              required:
              - detail
  "/api/news":
    get:
      summary: Get all news
      tags:
      - New
      responses:
        '200':
          description: List of news
          content:
            application/json:
              schema:
                type: object
                properties:
                  news:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        content:
                          type: text
                        category_id:
                          type: integer
    post:
      summary: Creates a new
      tags:
      - New
      security:
      - Bearer: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: New created
          content:
            application/json:
              schema:
                type: object
                properties:
                  new:
                    type: object
                    items:
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        content:
                          type: text
                        category_id:
                          type: integer
        '401':
          description: Unauthorized
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                new:
                  type: object
                  items:
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      content:
                        type: text
                      category_id:
                        type: integer
              required:
              - name
  "/api/news/{id}":
    put:
      summary: Updates a new
      tags:
      - New
      security:
      - Bearer: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  new:
                    type: object
                    items:
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        content:
                          type: text
                        category_id:
                          type: integer
        '401':
          description: Unauthorized
        '422':
          description: Invalid request
        '404':
          description: Not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                content:
                  type: text
                category_id:
                  type: integer
    delete:
      summary: Delete a new
      tags:
      - New
      security:
      - Bearer: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Not found
  "/api/news/:id/comments":
    get:
      summary: Get all comments of a new
      tags:
      - New
      responses:
        '200':
          description: List of comments of a new
          content:
            application/json:
              schema:
                type: object
                properties:
                  news:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        content:
                          type: text
                        category_id:
                          type: integer
                        comments:
                          type: object
                          items:
                            properties:
                              id:
                                type: integer
                              content:
                                type: string
  "/api/organization/public":
    get:
      summary: Gets an Organization
      tags:
      - Organization
      parameters:
      - name: organization
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Organization found
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  adress:
                    type: string
                  phone:
                    type: integer
                  email:
                    type: string
                  welcome_text:
                    type: text
                  about_us_text:
                    type: text
                  facebook_url:
                    type: string
                  instagram_url:
                    type: string
                  linkedin_url:
                    type: string
                required:
                - name
                - email
                - welcome_text
    put:
      summary: Updates an Organization
      tags:
      - Organization
      security:
      - bearer_auth: {}
      parameters:
      - name: organization
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Organization updated
        '400':
          description: Parameter is missing or its value is empty
        '401':
          description: Unauthorized access.
  "/api/testimonials":
    get:
      summary: all testimonials
      tags:
      - Testimonials
      parameters:
      - name: page
        in: query
        description: Parameter used for paging
        schema:
          type: integer
      responses:
        '200':
          description: success status when getting all users (no token required)
    post:
      summary: creates a testimonial
      tags:
      - Testimonials
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: testimonial created
        '400':
          description: bad request status if not pass the required parameters or sends
            some invalid parameter
        '401':
          description: unauthorized status if you do not have a token or are a client
            user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                content:
                  type: string
              required:
              - name
              - content
  "/api/testimonials/{testimonial_id}":
    put:
      summary: update an existing testimonial
      tags:
      - Testimonials
      security:
      - bearer_auth: []
      parameters:
      - name: testimonial_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success status when testimonial updeted
        '401':
          description: unauthorized status if not have a token or are a client user
        '404':
          description: 'not found status if testimonial do not exist '
        '422':
          description: unprocessable entity status if not pass the required parameters
            or sends some invalid parameter
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                content:
                  type: string
              required:
              - name
              - content
    delete:
      summary: delete an existing testimonial
      tags:
      - Testimonials
      security:
      - bearer_auth: []
      parameters:
      - name: testimonial_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success status when testimonial deleted
        '401':
          description: unauthorized status if not have a token or are a client user
        '404':
          description: 'not found status if testimonial do not exist '
  "/api/users":
    get:
      summary: returns all users
      tags:
      - Users
      security:
      - bearer_auth: {}
      responses:
        '200 ':
          description: show all users as Admin
          content:
            application/json:
              example:
                users:
                - id: 1
                  first_name: Guido
                  last_name: Medina
                  email: guido@gmail.com
                  role:
                    id: 1
                    name: admin
                    description: 'null'
                  image: myprofileimage.com/image.jpg
                - id: 2
                  first_name: Antonio
                  last_name: Porchia
                  email: antonio@gmail.com
                  role:
                    id: 1
                    name: client
                    description: 'null'
                  image: myprofileimage.com/image.jpg
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                        first_name:
                          type: string
                        last_name:
                          type: string
                        role:
                          type: object
                          items:
                            id:
                              type: integer
                            name:
                              type: string
                            description:
                              type: string
                        image:
                          type: string
        '200':
          description: show all users as Client
          content:
            application/json:
              example:
                users:
                - id: 1
                  first_name: Guido
                  last_name: Medina
                - id: 2
                  first_name: Antonio
                  last_name: Porchia
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                        first_name:
                          type: string
                        last_name:
                          type: string
        '401':
          description: Not a logged in user
  "/api/users/{id}":
    get:
      summary: Get user
      tags:
      - Users
      security:
      - bearer_auth: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: show user details
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      first_name:
                        type: string
                      last_name:
                        type: string
                      email:
                        type: string
                      role:
                        type: object
                        properties:
                          id:
                            type: integer
                          name:
                            type: string
                          description:
                            type: string
                      image:
                        type: string
        '401':
          description: unauthorized
        '404':
          description: not found
servers:
- url: http://localhost:3000
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      name: Authorize
